version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - gradle clean check
  build:
    commands:
      - gradle build
artifacts:
  type: zip
  files:
    - appspec.yml
    - template.yml
    - scripts/*
    - build/libs/ROOT.war
